title: Muhip Ege CAGLIDIL # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: Data solution specialist # your text below (remove <br> elements if you don't need line breaks)
  Hi There, this is my portfolio page. 
  <br><br>
I design, make it beeetter. And eveeen better 
  <br><br>
  <a href="https://www.linkedin.com/in/muhip-ege-%C3%A7a%C4%9Fl%C4%B1dil-8b6ab29a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
